behaviors:
  Bee-havior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1000
      buffer_size: 109600
      learning_rate: 1.0e-5
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 328
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 300000000
    time_horizon: 64
    summary_freq: 5000